# fly.toml app configuration file generated for puhelinluettelo-backend-morning-flower-9060 on 2024-06-29T19:53:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puhelinluettelo-backend-morning-flower-9060'
primary_region = 'ams'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
